# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-19 20:40
from __future__ import unicode_literals

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_ticket_customfields'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('createdBy', models.EmailField(default=b'system@justto.com', max_length=254, verbose_name=b'Criado por')),
                ('createdAt', models.DateField(auto_now_add=True, verbose_name=b'Criado em')),
                ('updatedBy', models.EmailField(default=b'system@justto.com', max_length=254, verbose_name=b'Atualizado por')),
                ('updatedAt', models.DateField(auto_now=True, verbose_name=b'Atualizado em')),
                ('person', models.CharField(choices=[(b'NATURAL', b'Pessoa F\xc3\xadsica'), (b'LEGAL', b'Pessoa Jur\xc3\xaddica')], default=b'NATURAL', max_length=10, verbose_name=b'Pessoa')),
                ('name', models.CharField(max_length=100, verbose_name=b'Nome')),
                ('legalId', models.CharField(max_length=25, unique=True, verbose_name=b'Documento')),
                ('username', models.CharField(max_length=25, unique=True, verbose_name=b'Usu\xc3\xa1rio')),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['username'],
                'verbose_name': 'Usu\xe1rio',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
