# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-19 22:51
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='counterparties',
            field=models.ManyToManyField(related_name='ticketsAsCounterpart', to=settings.AUTH_USER_MODEL, verbose_name=b'Contrapartes'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='defendants',
            field=models.ManyToManyField(related_name='ticketsAsDefendant', to=settings.AUTH_USER_MODEL, verbose_name=b'R\xc3\xa9us'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='lawyers',
            field=models.ManyToManyField(related_name='ticketsAsLawyer', to=settings.AUTH_USER_MODEL, verbose_name=b'Advogados'),
        ),
    ]
