# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-24 21:17
from __future__ import unicode_literals

import django.contrib.postgres.fields.hstore
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_user_customfields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='customFields',
            field=django.contrib.postgres.fields.hstore.HStoreField(blank=True, null=True, verbose_name=b'Campos Customizaveis'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=25, unique=True, verbose_name=b'Usuario'),
        ),
    ]
